---
- hosts: "all"
  remote_user: root
  tasks:
  - include_vars:  "/var/lib/awx/projects/ansible_rpi_library/group_vars/DEV/all"
  - include_vars:  "/var/lib/awx/projects/ansible_rpi_library/group_vars/DEV/vault"
  - include:  "{{ flask_location }}/flask_full_install.yml"
